import {readFile,writeFile,mkdir,readdir,unlink} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
const {marked}=await import(process.env.MARKED_PATH?pathToFileURL(process.env.MARKED_PATH).href:'marked');
const site=JSON.parse(await readFile('content/site.json','utf8'));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const posts=[];
for(const file of await readdir('content')){if(!/^\d.*\.md$/.test(file))continue;const source=await readFile('content/'+file,'utf8');const match=source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);if(!match)throw Error('Missing metadata: '+file);const meta=Object.fromEntries(match[1].split(/\r?\n/).map(l=>{const i=l.indexOf(':');return[l.slice(0,i).trim(),l.slice(i+1).trim()]}));if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(meta.slug))throw Error('Invalid slug');posts.push({...meta,body:marked.parse(match[2])})}
posts.sort((a,b)=>b.date.localeCompare(a.date));
const publishedPosts=posts.filter(p=>p.sample!=='true');
const listedPosts=publishedPosts.length?publishedPosts:posts;
if(new Set(posts.map(p=>p.slug)).size!==posts.length)throw Error('Duplicate post slug');
// Remove only generated article entrypoints after a post is renamed or deleted.
await mkdir('dist/blog',{recursive:true});
for(const entry of await readdir('dist/blog',{withFileTypes:true})){if(entry.isDirectory()&&!posts.some(p=>p.slug===entry.name)){try{await unlink('dist/blog/'+entry.name+'/index.html')}catch(e){if(e.code!=='ENOENT')throw e}}}
const nav=(base,current)=>`<a class="skip" href="#main">Skip to content</a><header class="nav"><a class="home-mark" href="${base}" ${current==='home'?'aria-current="page"':''}>home</a><nav class="nav-links" aria-label="Main navigation"><a href="${base}about/" ${current==='about'?'aria-current="page"':''}>about me</a><a href="${base}blog/" ${current==='blog'?'aria-current="page"':''}>blog</a></nav></header>`;
const footer=()=>`<footer><span>© ${new Date().getFullYear()} ${esc(site.name)}</span><div><a href="${site.github}">GitHub ↗</a><a href="${site.linkedin}">LinkedIn ↗</a></div></footer>`;
const doc=(title,body,base='./',current='home',script=false)=>`<!doctype html><html lang="en" class="no-js"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | ${esc(site.name)}</title><meta name="description" content="${esc(site.intro)}"><meta name="theme-color" content="#f6f7f2"><link rel="icon" href="${base}favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${base}style.css">${script?`<link rel="preload" as="image" href="${base}assets/mountains.webp"><script src="${base}motion.js" defer></script>`:''}</head><body class="${current==='home'?'home':'inner'}">${nav(base,current)}${body}${footer()}</body></html>`;
const rows=(items,base)=>items.map(p=>`<a class="post" data-post-tag="${esc(p.tag)}" href="${base}blog/${p.slug}/"><div class="post-meta"><time datetime="${p.date}">${new Date(p.date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})}</time><span class="tag">${p.sample==='true'?'Sample · ':''}${esc(p.tag)}</span></div><div><h3>${esc(p.title)}</h3>${p.summary?`<p>${esc(p.summary)}</p>`:''}</div><span class="post-arrow" aria-hidden="true">↗</span></a>`).join('');
await mkdir('dist/blog',{recursive:true});await mkdir('dist/about',{recursive:true});
await writeFile('dist/index.html',doc('Home',`<main id="main"><section class="journey" aria-label="Mountain introduction"><div class="scene"><img class="landscape" src="./assets/mountains.webp" width="1536" height="1024" alt="Layered green mountain ridges made of textured paper, fading into mist" fetchpriority="high"><div class="hero-copy"><div class="eyebrow">Principal Software Engineer</div><h1>${esc(site.headline)}</h1><p>${esc(site.heroIntro)}</p></div><a class="scroll-cue" href="./blog/">Read the blog</a></div></section><div class="runner" aria-hidden="true"></div><section class="intro" id="about"><div class="portrait">${site.portrait?`<img src="${esc(site.portrait)}" alt="${esc(site.name)}" width="240" height="300">`:'<span class="portrait-placeholder">mb.</span><span class="portrait-label">Portrait to come</span>'}</div><div class="intro-copy"><div class="eyebrow">Hi, I’m Matthew.</div><h2>${esc(site.introHeading)} <em>${esc(site.introEmphasis)}</em></h2><p>${esc(site.intro)}</p><p class="intro-aside">${esc(site.introAside)}</p><a class="text-link" href="./about/">A little about me <span aria-hidden="true">↗</span></a></div></section><section class="writing" aria-labelledby="latest"><div class="section-heading"><h2 class="section-title" id="latest">Blog.</h2><a class="text-link" href="./blog/">All writing <span aria-hidden="true">↗</span></a></div>${rows(listedPosts.slice(0,3),'./')}</section></main>`,'./','home',true));
await writeFile('dist/about/index.html',doc('About me',`<main class="page article" id="main"><h1>Hello, I'm Matthew.</h1><div class="prose">${marked.parse(await readFile('content/about.md','utf8'))}</div><div class="about-links"><a class="text-link" href="${site.github}">GitHub ↗</a><a class="text-link" href="${site.linkedin}">LinkedIn ↗</a></div></main>`,'../','about'));
const tags=[...new Set(listedPosts.map(p=>p.tag))].sort((a,b)=>a.localeCompare(b));
const tagSidebar=`<aside class="tag-sidebar" aria-label="Filter posts"><h2>Explore by topic</h2><nav data-tag-filters aria-label="Blog tags"><a href="./" data-tag="" aria-current="true">All posts <span>${listedPosts.length}</span></a>${tags.map(tag=>`<a href="?tag=${encodeURIComponent(tag)}" data-tag="${esc(tag)}">${esc(tag)} <span>${listedPosts.filter(p=>p.tag===tag).length}</span></a>`).join('')}</nav></aside>`;
await writeFile('dist/blog/index.html',doc('Blog',`<main class="page blog-page" id="main"><div class="eyebrow">Investigations & observations</div><h1>Blog.</h1><p class="lede">Things I'm exploring, building, and learning along the way.</p><div class="blog-layout">${tagSidebar}<section aria-label="Blog posts"><p class="filter-status" data-filter-status role="status" aria-live="polite">${listedPosts.length} ${listedPosts.length===1?'post':'posts'}</p>${rows(listedPosts,'../')}</section></div><script src="../blog-filter.js" defer></script></main>`,'../','blog'));
for(const p of posts){await mkdir('dist/blog/'+p.slug,{recursive:true});await writeFile('dist/blog/'+p.slug+'/index.html',doc(p.title,`<main class="page article" id="main"><a class="text-link" href="../">← All writing</a><div class="eyebrow" style="margin-top:45px">${esc(p.tag)} · <time datetime="${p.date}">${esc(p.date)}</time></div><h1>${esc(p.title)}</h1>${p.summary?`<p class="lede">${esc(p.summary)}</p>`:''}${p.sample==='true'?'<aside class="sample-note">Sample article — placeholder content for this first version.</aside>':''}<article class="prose">${p.body}</article></main>`,'../../','blog'))}
await writeFile('dist/404.html',doc('Page not found','<main class="page" id="main"><h1>A little off the trail.</h1><p>This page could not be found. Use your browser’s back button to return.</p></main>','./','blog'));
console.log(`Built home, about, blog and ${posts.length} articles.`);


